name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Set up environment variables
      run: |
        echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_mock_key" >> $GITHUB_ENV
        echo "STRIPE_SECRET_KEY=sk_test_mock_key" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=test-password-123" >> $GITHUB_ENV
        echo "UPSTASH_REDIS_REST_URL=http://localhost:6379" >> $GITHUB_ENV
        echo "UPSTASH_REDIS_REST_TOKEN=mock-token" >> $GITHUB_ENV

    - name: Run Playwright tests
      run: npm run test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30